version: '3.7'

services:
  cannabis-db:
    image: postgres:12
    environment:
      - POSTGRES_DB=cannabis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
